config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :new, :create, :show, :edit, :update]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
    resources :order_items, only: [:new, :create]
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show, :index, :create]
    end
  end
  
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :supplier
  has_many :order_items
  has_many :orders, through: :order_items
  validates :name, :sku, :weight, :width, :height, :depth, presence: true
  validates :sku, length: {in: 20..20, message: 'deve conter 20 caracteres'}
  validates :sku, uniqueness: true
  validates :weight, :width, :height, :depth, comparison: {greater_than: 0, message: 'deve ser maior que 0'} 
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController
    before_action :authenticate_user!, only: [:index]

    def index
        @product_models = ProductModel.all
    end

    def new
        @product_model = ProductModel.new
        @suppliers_ordened = Supplier.order(:name)
    end

    def create
        
        @product_model = ProductModel.new(product_model_params)
        if @product_model.save
            redirect_to(product_models_path, notice: 'Modelo de produto cadastrado com sucesso!')
        else
            @suppliers_ordened = Supplier.order(:name)
            flash.now[:notice] = 'Não foi possível cadastrar o modelo de produto!'
            render 'new'
        end
    end

    def show
        @product_model = ProductModel.find(params[:id])
    end

    def edit
        @product_model = ProductModel.find(params[:id])
        @suppliers_ordened = Supplier.order(:name)
    end

    def update
        @product_model = ProductModel.find(params[:id])
        if @product_model.update(product_model_params)
            redirect_to @product_model, notice: 'Modelo de produto atualizado com sucesso!'
        else
            @suppliers_ordened = Supplier.order(:name)
            flash.now[:notice] = 'Não foi possível atualizar o modelo de produto.'
            render 'new'
        end
    end

    private

    def product_model_params
        params.require(:product_model).permit(:name, :weight, :width, :height, :depth, :sku, :supplier_id)
    end

    

   
end

app/views/product_models/edit.html.erb
<% if @product_model.errors.any? %>
        <p>Verifique os erros:</p>
    <ul>
        <% @product_model.errors.full_messages.each do |msg|%>
            <li> <%= msg %>. </li>
        <% end %>
    </ul>
<% end %>

<%= form_with(model: @product_model) do |f| %>
    
    <div>
        <%= f.label :name %>
        <%= f.text_area :name %> <br>
    </div>

    <div>
        <%= f.label :weight %>
        <%= f.number_field :weight %> <br>
    </div>

    <div>
        <%= f.label :width %>
        <%= f.number_field :width %> <br>
    </div>

    <div>
        <%= f.label :height %>
        <%= f.number_field :height %> <br>
    </div>

    <div>
        <%= f.label :depth %>
        <%= f.number_field :depth %> <br>
    </div>

    <div>
        <%= f.label :sku %>
        <%= f.text_field :sku %> <br>
    </div>

    <div>
        <%= f.label :supplier_id, 'Fornecedor' %>
        <%= f.collection_select :supplier_id, @suppliers_ordened, :id, :brand_name %> <br>
    </div>

    <div>
        <%= f.submit %>
    </div>


<% end %>

app/views/product_models/index.html.erb
<h2> Modelos de produtos </h2>

<section id="product_models">

<div>
    <%= link_to 'Cadastrar novo modelo de produto', new_product_model_path %>
</div>

<% if @product_models.any? %>

    
        <% @product_models.each do |p| %>
        <div>

            <dl>
                <dt><%=ProductModel.model_name.human%>: </dt>
                <dd> <%= link_to p.name, product_model_path(p.id) %> </dd> <br>
                <dt><%=ProductModel.human_attribute_name(:sku)%>: </dt>
                <dd> <%= p.sku %> </dd> <br>
                 <dt><%=ProductModel.human_attribute_name(:supplier)%>: </dt>
                <dd> <%= p.supplier.brand_name %> </dd> <br> <br>

            </dl>

        </div>
        <% end %>

<% else %>

   <p> Não há modelos de produtos cadastrados! </p>
   
<% end %>

</section>

app/views/product_models/new.html.erb
<% if @product_model.errors.any? %>
        <p>Verifique os erros:</p>
    <ul>
        <% @product_model.errors.full_messages.each do |msg|%>
            <li> <%= msg %>. </li>
        <% end %>
    </ul>
<% end %>

<%= form_with(model: @product_model) do |f| %>
    
    <div>
        <%= f.label :name %>
        <%= f.text_area :name %> <br>
    </div>

    <div>
        <%= f.label :weight %>
        <%= f.number_field :weight %> <br>
    </div>

    <div>
        <%= f.label :width %>
        <%= f.number_field :width %> <br>
    </div>

    <div>
        <%= f.label :height %>
        <%= f.number_field :height %> <br>
    </div>

    <div>
        <%= f.label :depth %>
        <%= f.number_field :depth %> <br>
    </div>

    <div>
        <%= f.label :sku %>
        <%= f.text_field :sku %> <br>
    </div>

    <div>
        <%= f.label :supplier_id %>
        <%= f.collection_select :supplier_id, @suppliers_ordened, :id, :brand_name %> <br>
    </div>

    <div>
        <%= f.submit %>
    </div>


<% end %>

app/views/product_models/show.html.erb
<h1>Modelo de Produto: <%= @product_model.name %> </h1>



<h3> <%= link_to 'Editar', edit_product_model_path(@product_model.id) %> 

<div>
    <dl>

    <dt><strong><%= ProductModel.human_attribute_name(:name)%>: </strong></dt>
    <dd> <%= @product_model.name %> </dd> <br>

    <dt><strong><%=ProductModel.human_attribute_name(:weight)%>: </strong></dt>
    <dd> <%= @product_model.weight %>g </dd> <br>

    <dt><strong><%=ProductModel.human_attribute_name(:sku)%>: </strong></dt>
    <dd> <%= @product_model.sku %> </dd> <br>

    <dt><strong>Dimensões: </strong></dt>
    <dd> <%= @product_model.width %>cm x <%= @product_model.height %>cm x <%= @product_model.depth %>cm </dd> <br>

    <dt><strong><%=ProductModel.human_attribute_name(:supplier_id)%>: </strong></dt>
    <dd> <%= @product_model.supplier.corporation_name %> </dd> <br>
    
    </dl>
</div>