config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :new, :create, :show, :edit, :update]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
    resources :order_items, only: [:new, :create]
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show, :index, :create]
    end
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :supplier
  belongs_to :warehouse
  belongs_to :user
  has_many :order_items
  has_many :product_models, through: :order_items
  validates :code, :estimated_delivery_date, presence: true
  before_validation :set_code, on: :create
  validate :estimated_delivery_date_is_future
  enum status: {pending: 0, delivered: 5, canceled: 10}

  private

  def set_code
    self.code = SecureRandom.alphanumeric(8).upcase
  end

  def estimated_delivery_date_is_future
    if self.estimated_delivery_date.present? && self.estimated_delivery_date <= Date.today
      self.errors.add(:estimated_delivery_date, "deve ser futura")
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order_and_check_user, only: [:update, :edit, :show, :delivered, :canceled]

  def new
    @warehouses = Warehouse.order(:name)
    @suppliers = Supplier.order(:name)
    @order = Order.new
  end

  def create
    @order_user = current_user
    @order = Order.new(params.require(:order).permit(:estimated_delivery_date, :warehouse_id, :supplier_id).merge(user_id: @order_user.id))
    if @order.save
      flash[:notice] = 'Pedido realizado com sucesso!'
      redirect_to(@order) 
    else
      @warehouses = Warehouse.order(:name)
      @suppliers = Supplier.order(:name)
      flash.now[:notice] = "Não foi possível cadastrar o pedido"
      render 'new'
    end
  end

  def show
  end

  def search
    @code = params["query"]
    @orders = Order.where("code LIKE ?", "%#{@code}%")
  end

  def index
    @orders = current_user.orders
  end

  def edit
    @warehouses = Warehouse.order(:name)
    @suppliers = Supplier.order(:name)
  end

  def update
    if @order.update(params.require(:order).permit(:estimated_delivery_date, :warehouse_id, :supplier_id))
      return redirect_to(@order, notice: 'Pedido atualizado com sucesso.')
    else
      flash.now[:notice] = "Não foi possível atualizar o pedido."
      render 'edit'
    end
  end

  def delivered
    @order.delivered!
    @order.order_items.each do |item|
      item.quantity.times do 
        @stock = StockProduct.create!(warehouse: @order.warehouse, product_model: item.product_model, order: @order)
      end
    end
    redirect_to(@order, notice: 'Pedido marcado como entregue')
  end

  def canceled
    @order.canceled!
    redirect_to(@order, notice: 'Pedido marcado como cancelado')
  end


  private
  
  def set_order_and_check_user
    @order = Order.find(params[:id])
    if @order.user != current_user
      redirect_to(root_path, alert: 'Não foi possível realizar a ação!')
    end
  end
end

app/views/orders/_form_order.html.erb
<%= form_with model: @order do |f| %>

   <div>
    <%= f.label :warehouse_id %>
    <%= f.collection_select :warehouse_id, @warehouses, :id, :full_description %>
  </div>

  <div>
    <%= f.label :supplier_id %>
    <%= f.collection_select :supplier_id, @suppliers, :id, :full_description %>
  </div>

   <div>
    <%= f.label :estimated_delivery_date %>
    <%= f.date_field :estimated_delivery_date %>
  </div>

   <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<dl>

  <dt><%= Order.human_attribute_name(:code) %>: </dt>
  <dd><%= link_to order.code, order %></dd>

  <dt><%=Order.human_attribute_name(:warehouse_id)%> destino:</dt> 
  <dd> <%= order.warehouse.full_description %> </dd> 

  <dt><%=Order.human_attribute_name(:supplier_id)%>:</dt>
  <dd> <%= order.supplier.full_description %>. </dd> 

  <dt><%=Order.human_attribute_name(:user_id)%>:</dt>
  <dd> <%= order.user.description %> </dd>

  <dt><%=Order.human_attribute_name(:estimated_delivery_date)%>:</dt>
  <dd> <%= I18n.localize(order.estimated_delivery_date, format: :long) %> </dd>

  <dt><%=Order.human_attribute_name(:status)%>:</dt>
  <dd> <%= I18n.t(order.status) %> 
 
</dl>

app/views/orders/edit.html.erb
<h1> Edição de pedido </h1>

<% if @order.errors.any? %>
  <ul>
  <% @order.errors.full_messages.each do |m| %>
    <li><%= m %></li>
  <% end %>
  </ul>
<% end %>

<%= render 'form_order' %>

   

app/views/orders/index.html.erb
<h1> Meus Pedidos </h1>

<% @orders.each do |order| %>
  <%= render order%>
<% end %>

app/views/orders/new.html.erb
<h1> Cadastro de pedido </h1>

<% if @order.errors.any? %>
  <ul>
  <% @order.errors.full_messages.each do |m| %>
    <li><%= m %></li>
  <% end %>
  </ul>
<% end %>

<%= form_with model: @order do |f| %>

   <div>
    <%= f.label :warehouse_id %>
    <%= f.collection_select :warehouse_id, @warehouses, :id, :full_description %>
  </div>

  <div>
    <%= f.label :supplier_id %>
    <%= f.collection_select :supplier_id, @suppliers, :id, :full_description %>
  </div>

   <div>
    <%= f.label :estimated_delivery_date %>
    <%= f.date_field :estimated_delivery_date %>
  </div>

   <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/search.html.erb
<h1> Resultados da busca por: <%= @code %> </h1>

<% if @orders.any? %>
 <p> <%=@orders.count%> <%=Order.model_name.human(count: @orders.count)%> <%= I18n.t(:found, count: @orders.count)%> </p>
  <% @orders.each do |order| %>
    <dl>
    <dt><%= Order.human_attribute_name(:code) %>: </dt>
    <dd><%=order.code%></dd>
    <dt><%= Order.human_attribute_name(:warehouse) %> destino:</dt>
    <dd><%=order.warehouse.full_description%></dd>
    <dt><%= Order.human_attribute_name(:supplier) %>:</dt>
    <dd><%=order.supplier.corporation_name%></dd>
  </dl>
  <% end%>
<%end%>

app/views/orders/show.html.erb
<h1> <%= Order.model_name.human %> - <%= @order.code %> </h1>
<dl>
  <dt><%= Order.human_attribute_name(:code) %>: </dt>
  <dd><%= link_to @order.code, @order %></dd>

  <dt><%=Order.human_attribute_name(:warehouse_id)%> destino:</dt>
  <dd> <%= @order.warehouse.full_description %> </dd>

  <dt><%=Order.human_attribute_name(:supplier_id)%>:</dt>
  <dd> <%= @order.supplier.full_description %>. </dd>

  <dt><%=Order.human_attribute_name(:user_id)%>:</dt>
  <dd> <%= @order.user.description %> </dd>

  <dt><%=Order.human_attribute_name(:estimated_delivery_date)%>:</dt>
  <dd> <%= I18n.localize(@order.estimated_delivery_date, format: :long) %> </dd>

  <dt><%=Order.human_attribute_name(:status)%>:</dt>
  <dd> <%= I18n.t(@order.status) %> </dd>
 
</dl>

<h2>Itens do pedido</h2>
<%= link_to 'Adicionar Item', new_order_order_item_path(@order.id) %> 
<div>
  <ul>
  <% @order.order_items.each do |item| %>
    <li><%= item.quantity %>x - <%= item.product_model.name%></li>
  <% end %>
  </ul>
</div>

<div>
  <% if @order.pending?%>
    <%= button_to 'Marcar como ENTREGUE', delivered_order_path(@order)%>
    <%= button_to 'Marcar como CANCELADO', canceled_order_path(@order)%>
  <% elsif @order.canceled? %>
    <%= button_to 'Marcar como ENTREGUE', delivered_order_path(@order)%>
  <% elsif @order.delivered? %>
    <%= button_to 'Marcar como CANCELADO', canceled_order_path(@order)%>
  <%end%>
</div>

<%= link_to 'Editar', edit_order_path(@order.id)%>