config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :new, :create, :show, :edit, :update]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
    resources :order_items, only: [:new, :create]
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show, :index, :create]
    end
  end
  
end

app/models/supplier.rb
class Supplier < ApplicationRecord
    has_many :product_models
    validates :corporation_name, :registration_number, :city, :state, :address, :email, presence: true
    validates :registration_number, uniqueness: true
    validates :registration_number, format: {with: /\d{2}\.\d{3}\.\d{3}\/\d{4}\-\d{2}/, message: 'deve ter o formato XY.XYZ.XYZ/XYZA-XYZ'}

    def full_description
        "#{corporation_name} - #{brand_name} | #{registration_number}"
    end

end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
    before_action :set_id, only: [:show, :edit, :update]
    

    def index
        @suppliers = Supplier.all
    end

    def new
        @supplier = Supplier.new
        
    end

    def show
        
    end

    def edit
        
    end

    def update
        
        if @supplier.update(supplier_params)
            redirect_to(supplier_path(@supplier.id), notice: 'Fornecedor atualizado com sucesso')
        else
            flash.now[:notice] = 'Não foi possível atualizar o fornecedor'
            render :edit
        end
    end

    def create
        @supplier = Supplier.new(supplier_params)

        if @supplier.save
            redirect_to(suppliers_path, notice: 'Fornecedor cadastrado com sucesso.')
        else
            flash.now[:notice] = 'Não foi possível cadastrar o fornecedor!'
            render :new
        end
    end

    private

    def set_id
        @supplier = Supplier.find(params[:id])
    end

    def supplier_params
        params.require(:supplier).permit(:corporation_name, :brand_name, :registration_number,
            :city, :email, :state, :address)
    end
end

app/views/suppliers/edit.html.erb
<h1> Edição de <%= @supplier.corporation_name %> </h1>

<% if @supplier.errors.any? %>
        <p>Verifique os erros:</p>
    <ul>
        <% @supplier.errors.full_messages.each do |msg|%>
            <li> <%= msg %>. </li>
        <% end %>
    </ul>
<% end %>

<%= form_with model: @supplier do |f| %>

    <%= f.label :corporation_name %>
    <%= f.text_field :corporation_name %> <br>

    <%= f.label :brand_name %>
    <%= f.text_field :brand_name %> <br>

    <%= f.label :registration_number %>
    <%= f.text_field :registration_number %> <br>

    <%= f.label :address %>
    <%= f.text_field :address %> <br>

    <%= f.label :city %>
    <%= f.text_field :city %> <br>

    <%= f.label :state %>
    <%= f.text_field :state %> <br>

    <%= f.label :email %>
    <%= f.text_field :email %> <br>

    <%= f.submit %>

<% end %>

app/views/suppliers/index.html.erb
<section id="suppliers">

<h2> Fornecedores </h2>

<div>
    <%= link_to('Cadastrar fornecedor', new_supplier_path)%>
</div>


<% if @suppliers.any? %>

    
        <% @suppliers.each do |s| %>
        <div>

            <dl>
                <dt>Razão social: </dt>
                <dd> <%= link_to(s.corporation_name, s) %> </dd>
                <dd> <%= s.city %>/<%= s.state %> </dd>

                <dt>E-mail: </dt>
                <dd> <%= s.email %> </dd> <br>

            </dl>

        </div>
        <% end %>

<% else %>

   <p> Não há fornecedores cadastrados! </p>
   
<% end %>

</section>

app/views/suppliers/new.html.erb
<%= form_with model: @supplier do |f| %>

    <%= f.label :corporation_name %>
    <%= f.text_field :corporation_name %>

    <%= f.label :brand_name %>
    <%= f.text_field :brand_name %>

    <%= f.label :registration_number %>
    <%= f.text_field :registration_number %>

    <%= f.label :address %>
    <%= f.text_field :address %>

    <%= f.label :city %>
    <%= f.text_field :city %>

    <%= f.label :state %>
    <%= f.text_field :state %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.submit %>

<% end %>

app/views/suppliers/show.html.erb
<h1> Fornecedor <% @supplier.corporation_name %> </h1>

<h3> <%= link_to 'Editar Fornecedor', edit_supplier_path(@supplier.id) %> 

<div>
    <dl>

    <dt> Razão Social:</dt>
    <dd> <%= @supplier.corporation_name %> </dd> <br>

    <dt>Nome Fantasia:</dt>
    <dd> <%= @supplier.brand_name %> </dd> <br>

    <dt>CNPJ:</dt>
    <dd> <%= @supplier.registration_number %> </dd> <br>

    <dt>Endereço:</dt>
    <dd> <%= @supplier.address %> </dd> <br>

    <dt>Cidade/UF:</dt>
    <dd> <%= @supplier.city %>/<%= @supplier.state %> </dd> <br>

    <dt>E-mail:</dt>
    <dd> <%= @supplier.email %> </dd> <br>
    
    </dl>
</div>