config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :new, :create, :show, :edit, :update]
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    get 'search', on: :collection
    post 'delivered', on: :member
    post 'canceled', on: :member
    resources :order_items, only: [:new, :create]
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show, :index, :create]
    end
  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarehouseApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <header>
      <%= link_to root_path do %>
        <h1> Galpões & Estoque </h1>
      <% end %>
      <nav>
        <%= link_to('Fornecedores', suppliers_path) %> <br>
        <%= link_to('Modelos de Produtos', product_models_path) %> <br>
        <%= link_to('Registrar pedido', new_order_path) %> <br>
        <%= link_to('Meus Pedidos', orders_path) %> <br>

        <% if user_signed_in? %>
          <%= current_user.description %>
          <%= form_with(url: search_orders_path, method: :get) do |f| %>
            <%= f.label :query, 'Procurar pedido' %>
            <%= f.text_field :query %>
            <%= f.submit 'Buscar' %>
          <%end%>
          <%= button_to('Sair', destroy_user_session_path, method: :delete) %> <br>
        <% else %>
           <%= link_to('Entrar', new_user_session_path) %> <br>
        <% end %>
      </nav>
    </header>

    <main>
    
      <div>
      <%=alert%>
      <%=notice%>
      </div>

    <%= yield %>
    </main>
  </body>
</html>